name = "rald-auth"
main = "dist/worker.mjs"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "auth.ostloop.name.ng/*", zone_name = "ostloop.name.ng" }
]

# Routes / custom domains can be added later, e.g.:
# routes = [
#   { pattern = "api.example.com/*", zone_name = "example.com" }
# ]
